#!/usr/bin/env python3
##
## EPITECH PROJECT, 2021
## B-MAT-200-LIL-2-1-106bombyx-simon.auduberteau
## File description:
## 106bombyx
##

import sys
from math import *
from solving import *

def help():
    print("USAGE\n    ./106bombyx n [k | i0 i1]")
    print("\nDESCRIPTION")
    print("    n      number of the first generation individuals")
    print("    k      growth rate from 1 to 4")
    print("    i0     initial generation (included)")
    print("    i1     final generation (included)")
    exit(0)

def is_intarg(str):
    try:
        int(str)
        return True
    except ValueError:
        return False

def is_floatarg(str):
    try:
        float(str)
        return True
    except ValueError:
        return False

def error():
    if (len(sys.argv) != 3 and len(sys.argv) != 4):
        sys.stderr.write("Error: arguments, please use \"-h\"\n")
        sys.exit(84)
    if (len(sys.argv) == 3):
        if not is_intarg(sys.argv[1]):
            sys.stderr.write("Error Arguments.\n")
            sys.exit(84)
        if not is_intarg(sys.argv[2]) and not is_floatarg(sys.argv[2]):
            sys.stderr.write("Error Arguments.\n")
            sys.exit(84)
        if float(sys.argv[2]) < 1 or float(sys.argv[2]) > 4:
            sys.stderr.write("Error Arguments.\n")
            sys.exit(84)
    if (len(sys.argv) == 4):
        for argv in sys.argv[1:]:
            if not is_intarg(argv):
                sys.stderr.write("Error Arguments.\n")
                sys.exit(84)
        if int(sys.argv[2]) > int(sys.argv[3]):
            sys.stderr.write("Error: Arguments.\n")
            sys.exit(84)

def main():
    if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
        help()
    else:
        error()
        calcul()
    
if __name__ == "__main__":
    main()