#!/usr/bin/env python3
##
## EPITECH PROJECT, 2022
## delivery [WSL: Ubuntu-20.04]
## File description:
## 205neutrinos
##

import sys
import error, data, printing, calculs

def help():
    print("USAGE\n    ./206neutrinos n a h sd")
    print("\nDESCRIPTION")
    print("    n        number of values")
    print("    a        arithmetic mean")
    print("    h        harmonic mean")
    print("    sd       standard deviation")
    exit(0)

def main():
    """
    """
    if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
        help()
    error.error()

    datas = data.Data()
    userInput = 0

    while True:
        print("Enter next value: ", end='')
        userInput = input()
        if userInput == "END":
            break
        datas.nbValues += 1
        error.errorInput(userInput)
        calculs.calcul(int(userInput), datas)
        printing.printing(datas)
        

if __name__ == "__main__":

    main()
