#!/usr/bin/env python3
##
## EPITECH PROJECT, 2021
## B-MAT-200-LIL-2-1-108trigo-simon.auduberteau
## File description:
## 108trigo
##

import sys
from math import *
from solving import *

def help():
    print("USAGE\n    ./108trigo fun a0 a1 a2 ...")
    print("\nDESCRIPTION")
    print("    fun     function to be applied, among at least \"EXP\", \"COS\", \"SIN\", \"COSH\"")
    print("            and \"SINH\"")
    print("    ai      coeficients of the matrix")
    sys.exit(0)

def is_intarg(str):
    try:
        int(str)
        return True
    except ValueError:
        return False

def error():
    if len(sys.argv) == 1:
        sys.stderr.write("Error: Not enough argument\n")
        sys.exit(84)
    if (len(sys.argv) - 2) != 4 and (len(sys.argv) - 2) != 1 and (len(sys.argv) - 2) != 9:
            sys.exit(84)
    if sys.argv[1] != "EXP" and sys.argv[1] != "COS" and sys.argv[1] != "SIN" and sys.argv[1] != "COSH" and sys.argv[1] != "SINH":
        sys.stderr.write("Error: Invalid first argument\n")
        sys.exit(84)
    for str in sys.argv[2:]:
        if not is_intarg(str):
            sys.stderr.write("Error arguments\n")
            sys.exit(84)

def main():
    if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
        help()
    else:
        error()
        dispatch_fct(sys.argv)

if __name__ == "__main__":
    main()