##
## EPITECH PROJECT, 2022
## delivery [WSL: Ubuntu-20.04]
## File description:
## Makefile
##

# cp -f groundhog.py groundhog

# fclean: rm groundhog

MAIN = trade.py

NAME = trade

all: $(NAME)

$(NAME):
	cp $(MAIN) $(NAME)
	chmod +x $(NAME)

fclean:
	rm -f $(NAME)

re: fclean all