##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile
##

all:
	make -C ncurses/
	make -C sdl2/
	make -C sfml/

re:
	make re -C ncurses/
	make re -C sfml/
	make re -C sdl2/

clean:
	make clean -C ncurses/
	make clean -C sfml/
	make clean -C sdl2/

fclean:
	make fclean -C ncurses/
	make fclean -C sfml/
	make fclean -C sdl2/

ncurses:
	make -C ncurses/

sdl2:
	make -C sdl2/

sfml:
	make -C sfml/

.PHONY: ncurses sdl2 sfml