##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile
##

all:
	make -C pacman/
	make -C nibbler/
	make -C centipede/

re:
	make re -C pacman/
	make re -C nibbler/
	make re -C centipede/

clean:
	make clean -C pacman/
	make clean -C nibbler/
	make clean -C centipede/

fclean:
	make fclean -C pacman/
	make fclean -C nibbler/
	make fclean -C centipede/

pacman:
	make -C pacman/

nibbler:
	make -C nibbler/

centipede:
	make -C centipede/

.PHONY: pacman nibbler centipede