##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile
##

all:
	make -C graphicals/
	make -C games/
	make -C src/

re:
	make re -C graphicals/
	make re -C games/
	make re -C src/

clean:
	make clean -C graphicals/
	make clean -C games/
	make clean -C src/

fclean:
	make fclean -C graphicals/
	make fclean -C games/
	make fclean -C src/

games:
	make -C games/

graphicals:
	make -C graphicals/

core:
	make -C src/

.PHONY: games graphicals core