#!/usr/bin/env python3
##
## EPITECH PROJECT, 2022
## delivery [WSL: Ubuntu-20.04]
## File description:
## 204ducks
##

import error, calculs
import sys

def help():
    print("USAGE\n    ./204ducks a")
    print("\nDESCRIPTION")
    print("    a\tconstant")
    exit(0)

def main():
    """
    """
    if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
        help()
    else:
        error.error()
        calculs.calcul(float(sys.argv[1]))

if __name__ == "__main__":
    main()